velopert/velog-client

- src/containers/velog/hooks/useApplyVelogConfig.ts
useApplyVelogConfig 에서 null 체킹이 제대로 안되고있었음.
> Fix crash on invalid user

- src/components/common/MarkdownRender.tsx
> Fix suspected bug for linkedpost crash

- src/containers/post/PostCommentsWriteContainer.tsx
- src/lib/hooks/useRequireLogin.ts
> Require login on comment

- src/components/common/UserProfile.tsx
> Include protocol to homepage link if missing

- src/components/common/Typography.tsx
Apply code style inside ul or ol
> Resolves #175

- src/components/common/MarkdownRender.tsx
> Resolve #169

- src/containers/auth/AuthModalContainer.tsx
> Resolves #205

- src/components/auth/AuthEmailSuccess.tsx
- src/components/common/Button.tsx
- src/components/common/EditRemoveGroup.tsx
- src/components/common/SpinnerBlock.tsx
- src/components/home/HomeMobileHeadExtra.tsx
- src/components/home/TimeframePicker.tsx
- src/components/post/PostSeriesInfo.tsx
- src/components/register/RegisterTemplate.tsx
- src/components/search/SearchResultInfo.tsx
- src/components/velog/SeriesItem.tsx
- src/components/velog/VelogTab.tsx
- src/components/write/PublishScreenTemplate.tsx
color: initial;로 되있던 코드를 color: inherit으로 바꿔 h4의 흰색 컬러를 받아오도록 했습니다.
> 다크모드일때 시리즈 제목이 안보이는 에러 수정

- src/components/write/PublishSeriesCreate.tsx
- src/components/write/__tests__/PublishSeriesCreate.test.tsx
제목이 없는 시리즈가 생성되어 삭제도 불가능한 이슈가 있어 클라이언트에서 수정하였습니다.
서버도 수정하는게 좋을 것 같아요!
> 제목 없는 시리즈가 생성되지 않도록 수정하였습니다

- src/components/setting/SettingEmailRow.tsx
todo: make a spinner with button. How did I not make that in the past????
> fix: disable form when loading

- src/components/common/FollowButton.tsx
> fix: set initial state for follow

- src/components/common/FlatPostCard.tsx
- src/components/common/PostCard.tsx
- src/components/post/PostCommentItem.tsx
- src/containers/post/RelatedPost.tsx
- src/lib/graphql/__data__/post.data.ts
- src/lib/graphql/post.ts
> feat: change card writer name

- src/lib/graphql/post.ts
Fix #476 
코멘트 관련부분 쿼리 오류로 현재 업로드가 정상적으로 진행되지 않고 있습니다.
> Fix post.ts 쿼리 오타

- src/components/common/FlatPostCard.tsx
- src/components/common/PostCard.tsx
- Nullable한 display_name case 처리
> fix: handle nullable display_name

- src/components/base/Header.tsx
> fix: refetch notification count when icon click

- src/components/base/Header.tsx
> fix: notification count query in header

- src/components/write/WriteMarkdownEditor.tsx
- src/containers/write/MarkdownEditorContainer.tsx
- temp save 한 뒤에 값을 올바르게 불러올 수 있도록 수정
> fix: improve temp save functionality

- src/containers/write/MarkdownEditorContainer.tsx
- 수정 -> 출간 -> 수정 할때 저장 안되던 버그 수정
> fix: Improve temp save functionality and remove notification when auto save

- src/containers/write/MarkdownEditorContainer.tsx
- 임시 저장버튼을 눌렀을때, 이전 is_private, is_temp 값 계속 사용하도록 변경
> feat: Add isPrivate, isTemp flag

- src/containers/velog/SeriesPosts.tsx
> 시리즈 삭제 UE 개선

- src/components/post/PostHead.tsx
- src/containers/post/PostViewer.tsx
- src/containers/velog/SeriesPosts.tsx
- 게시글 삭제 시 로딩 화면 추가
- 삭제 성공 및 실패 시 toast
> 게시글 삭제 UE 개선

- src/components/write/WriteMarkdownEditor.tsx
- src/lib/remark/prismPlugin.js
- support dockerfile highlighting
> feat: Add support for Dockerfile syntax highlighting

- src/components/write/TagInput.tsx
> 태그 최대 길이 제한

- src/components/write/TagInput.tsx
- src/containers/register/RegisterFormContainer.tsx
- src/lib/utils.ts
> input 값 검증하기

- src/components/write/TagInput.tsx
> 태그가 비어있을 경우 삭제되지 않던 문제를 수정
